Models/Cataglory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using static WebApplication1.UniqueAttribute.UniqueAttribute;

namespace WebApplication1.Models
{
    public class Cataglory
    {
		[Key]
		public int Id { get; set; }
		[Required]
		public string Description { get; set; }

		[Required]
		[Unique]
		public string Name { get; set; }
	}
}

Controllers/CataglorysController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.viewmodel;

namespace WebApplication1.Controllers
{
    public class CataglorysController : Controller
    {
        // GET: Cataglory
        private ApplicationDbContext _context; // use ApplicationDbContext class to connect to database

        public CataglorysController()
        {
            _context = new ApplicationDbContext();
        }
        public ActionResult Index()
        {
            var cataglory = _context.cataglories.ToList();
            return View(cataglory);
        }
        

        [HttpGet]
        
        public ActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cataglory cataglory)
        {
            if(!ModelState.IsValid)
            {
                return View(cataglory); 
            }
            var newcataglory= new Cataglory()
            {
                Description = cataglory.Description,
                Name = cataglory.Name,
                
            };
            _context.cataglories.Add(newcataglory);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var cataglory = _context.cataglories
                .SingleOrDefault(t => t.Id == id);
            if (cataglory == null) return HttpNotFound();

            _context.cataglories.Remove(cataglory);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

           

            var cataglorYInDb = _context.cataglories
                .SingleOrDefault(t => t.Id == id);

            if (cataglorYInDb == null) return HttpNotFound();

            return View(cataglorYInDb);
        }

        [HttpPost]
        public ActionResult Edit(Cataglory cataglory)
        {
            if (!ModelState.IsValid)
            {
                
                return View(cataglory);
            }


            var todoInDb = _context.cataglories
                .SingleOrDefault(t => t.Id == cataglory.Id);

            if (todoInDb == null) return HttpNotFound();

            todoInDb.Description = cataglory.Description;
            todoInDb.Name = cataglory.Name;

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    [HttpGet]
    public ActionResult CheckCourse(int? id)
    {
      if (id == null)
        return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
      var checkCourse = _context.works
         .Where(t => t.CatagloryId == id)
         .Include(t => t.Courses)
         .Select(t => t.CourseId);
      ViewBag.CatagloryId = id;
      return View(checkCourse);
    }

    [HttpGet]
    public ActionResult AddCourse(int? id)
    {
      if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      if (_context.cataglories.SingleOrDefault(t => t.Id == id) == null)
        return HttpNotFound();

      var CourseInDb = _context.courses.ToList();
      var usersInTeam = _context.works         // User trong Team
         .Include(t => t.Courses)
         .Where(t => t.CourseId == id)
         .Select(t => t.User)
         .ToList();

      var viewModel = new CateloryCreateViewmodel()
      {
        CateloryId = (int)id,
        course = CourseInDb
      };
      return View(viewModel);
    }
    [HttpPost]
    public ActionResult AddMembers(work model)
    {
      var newwork = new work
      {
        CourseId = model.CourseId,
        CatagloryId = model.CatagloryId
      };

      _context.works.Add(newwork);
      _context.SaveChanges();

      return RedirectToAction("Members", new { id = model.CatagloryId });
    }
    [HttpGet]
    public ActionResult RemoveMember(int id, int courseid)
    {
      var teamUserToRemove = _context.works
        .SingleOrDefault(t => t.CatagloryId == id && t.CourseId == courseid);

      if (teamUserToRemove == null)
        return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);

      _context.works.Remove(teamUserToRemove);
      _context.SaveChanges();
      return RedirectToAction("Members", new { id = id });
    }
  }
}

Views/Cataglorys/Create.cshtml
@model WebApplication1.Models.Cataglory

@{
    ViewBag.Title = "Create";
}

<h2>Create new Cataglory</h2>


@using (Html.BeginForm("Create", "Cataglorys", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Cataglory</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "Enter Todo Name" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Description)
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control", @placeholder = "Enter Todo Description" })
            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
        </div>


        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

}

<div class="form-group">
    <a href="@Url.Action("Index", "Cataglorys")" class="btn btn-primary">
        <i class="fas fa-arrow-left"></i>

    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Cataglorys/Edit.cshtml
@model WebApplication1.Models.Cataglory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Cataglorys", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cataglory</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.Id)

        <div class="form-group">
            @Html.LabelFor(m => m.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div class="form-group">
    <a href="@Url.Action("Index", "Cataglorys")" class="btn btn-primary">
        <i class="fas fa-arrow-left"></i>

    </a>
 </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Views/Cataglorys/Index.cshtml
@model IEnumerable<WebApplication1.Models.Cataglory>

@{
    ViewBag.Title = "Index";
}

<h2>List Cataglory</h2>
<div class="form-group">
    @Html.ActionLink(
             "Create a new Cataglory",
             "Create",
             "Cataglorys",
             null,
             new { @class = "btn btn-primary" }
             )
</div>


<table class="table table-bordered">
    <tr>
       
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.Description
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id },new { @class = "btn btn-danger" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn - warning" })
            </td>
        </tr>
    }

</table>