Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.viewmodel;

namespace WebApplication1.Controllers
{
    public class CoursesController : Controller
    {
        private ApplicationDbContext _context; // use ApplicationDbContext class to connect to database

        public CoursesController()
        {
            _context = new ApplicationDbContext();
        }
    // GET: Courses

    public ActionResult Index()
    {
      var courses = _context.courses.ToList();
      return View(courses);
    }


    [HttpGet]

    public ActionResult Create()
    {

      return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(Course course)
    {
      if (!ModelState.IsValid)
      {
        return View(course);
      }
      var newourse = new Course()
      {

        Description = course.Description,
        Name = course.Name,
        StartDateTime = course.StartDateTime,
        EndDateTime =course.EndDateTime
      };
      
      _context.courses.Add(newourse);
      _context.SaveChanges();

      return RedirectToAction("Index");
    }
    public ActionResult Delete(int? id)
    {
      if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      var courseInDb = _context.courses
          .SingleOrDefault(t => t.Id == id);
      if (courseInDb == null) return HttpNotFound();

      _context.courses.Remove(courseInDb);
      _context.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpGet]
    public ActionResult Edit(int? id)
    {
      if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      var courseInDb = _context.courses
          .SingleOrDefault(t => t.Id == id);

      if (courseInDb == null) return HttpNotFound();

      return View(courseInDb);
    }

    [HttpPost]
    public ActionResult Edit(Course course)
    {
      if (!ModelState.IsValid)
      {
        return View(course);
      }
      var courseInDb = _context.courses
          .SingleOrDefault(t => t.Id == course.Id);

      if (courseInDb == null) return HttpNotFound();

      courseInDb.Description = course.Description;
      courseInDb.Name = course.Name;
      courseInDb.StartDateTime = course.StartDateTime;
      courseInDb.EndDateTime = course.EndDateTime;

      _context.SaveChanges();

      return RedirectToAction("Index");
    }
    
    public ActionResult Detail(int? id)
    {
      if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      var courseInDb = _context.toppics.Where(m => m.CourseId == id).ToList();
      if (courseInDb == null) return HttpNotFound();
      return View(courseInDb);
    }


    
  }
}

Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.viewmodel;

namespace WebApplication1.Controllers
{
	public class TopicsController : Controller
	{
		// GET: Topics
		private ApplicationDbContext _context; // use ApplicationDbContext class to connect to database

		public TopicsController()
		{
			_context = new ApplicationDbContext();
		}
		// GET: Courses

		public ActionResult Index()
		{
			var Topic = _context.toppics.Include(m => m.Course).ToList();
			return View(Topic);
		}


		[HttpGet]
		public ActionResult Create()
		{
			var viewModel = new ToppicCourseViewmodel()
			{
				Courses = _context.courses.ToList()
			};
			return View(viewModel);
		}

		[HttpPost]
		public ActionResult Create(Toppic toppic)
		{
			if (!ModelState.IsValid)
			{
				var viewModel = new ToppicCourseViewmodel()
				{
					Toppic = toppic,
					Courses = _context.courses.ToList()
				};
				return View(viewModel);
			}

			var newToppic = new Toppic()
			{
				Description = toppic.Description,
				Name = toppic.Name,
				CourseId = toppic.CourseId
			};

			_context.toppics.Add(newToppic);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Edit(int? id)
		{
			if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);


			var toppicInDb = _context.toppics
				.SingleOrDefault(t => t.Id == id);

			if (toppicInDb == null) return HttpNotFound();

			var viewModel = new ToppicCourseViewmodel()
			{
				Toppic = toppicInDb,
				Courses = _context.courses.ToList()
			};

			return View(viewModel);
		}

		[HttpPost]
		public ActionResult Edit(Toppic toppic)
		{
			if (!ModelState.IsValid)
			{
				var viewModel = new ToppicCourseViewmodel()
				{
					Toppic = toppic,
					Courses = _context.courses.ToList()
				};
				return View(viewModel);
			}


			var toppicInDb = _context.toppics
				.SingleOrDefault(t => t.Id == toppic.Id);
			if (toppicInDb == null) return HttpNotFound();

			toppicInDb.Description = toppic.Description;
			toppicInDb.Name = toppic.Name;
			toppicInDb.CourseId = toppic.CourseId;

			_context.SaveChanges();

			return RedirectToAction("Index");
		}
		public ActionResult Delete(int? id)
		{
			if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);


			var todo = _context.toppics
				.SingleOrDefault(t => t.Id == id);

			if (todo == null) return HttpNotFound();

			_context.toppics.Remove(todo);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
		[HttpGet]
		public ActionResult Create2(int? id)
		{
			if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			var CInDb = _context.courses.Where(m => m.Id == id);


			if (CInDb == null) return HttpNotFound();

			var viewModel = new ToppicCourseViewmodel()
			{
	
				Courses = CInDb
			};
			return View(viewModel);
		}
		[HttpPost]
		public ActionResult Create2(Toppic toppic)
		{
			if (!ModelState.IsValid)
			{
				var viewModel = new ToppicCourseViewmodel()
				{
					Toppic = toppic,
					Courses = _context.courses.ToList()
				};
				return View(viewModel);
			}

			var newToppic = new Toppic()
			{
				Description = toppic.Description,
				Name = toppic.Name,
				CourseId = toppic.CourseId
			};

			_context.toppics.Add(newToppic);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

	}
}

Views/Topics/Create.cshtml
@model WebApplication1.viewmodel.ToppicCourseViewmodel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Topics", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Toppic.Name)
        @Html.TextBoxFor(m => m.Toppic.Name, new { @class = "form-control", @placeholder = "Enter Todo Description" })
        @Html.ValidationMessageFor(m => m.Toppic.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Toppic.Description)
        @Html.TextBoxFor(m => m.Toppic.Description, new { @class = "form-control", @placeholder = "Enter Todo Description" })
        @Html.ValidationMessageFor(m => m.Toppic.Description, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Toppic.Course.Name)
        @Html.DropDownListFor(m => m.Toppic.CourseId,
            new SelectList(Model.Courses, "Id", "Name"),
            new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Toppic.CourseId, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
}
<div class="form-group">
    <a href="@Url.Action("Index", "Topics")" class="btn btn-primary">
        <i class="fas fa-arrow-left"></i>

    </a>
</div>

Views/Topics/CreateTopic.cshtml
@model WebApplication1.viewmodel.ToppicCourseViewmodel

@{
    ViewBag.Title = "CreateTopic";
}

<h2>CreateTopic</h2>

@using (Html.BeginForm("CreateTopic", "Topics", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Toppic.Name)
        @Html.TextBoxFor(m => m.Toppic.Name, new { @class = "form-control", @placeholder = "Enter Todo Description" })
        @Html.ValidationMessageFor(m => m.Toppic.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Toppic.Description)
        @Html.TextBoxFor(m => m.Toppic.Description, new { @class = "form-control", @placeholder = "Enter Todo Description" })
        @Html.ValidationMessageFor(m => m.Toppic.Description, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Toppic.Course.Name)
        @Html.DropDownListFor(m => m.Toppic.CourseId,
            new SelectList(Model.Courses, "Id", "Name"),
            new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Toppic.CourseId, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
}
<div class="form-group">
    <a href="@Url.Action("Index", "Courses")" class="btn btn-primary">
        <i class="fas fa-arrow-left"></i>

    </a>
</div>

Views/Topics/Edit.cshtml
@model WebApplication1.Models.Toppic

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Toppic</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="form-group">
    <a href="@Url.Action("Index", "Topics")" class="btn btn-primary">
        <i class="fas fa-arrow-left"></i>

    </a>
</div>

Views/Topics/Index.cshtml
@model IEnumerable<WebApplication1.Models.Toppic>

@{
    ViewBag.Title = "Index";
}

<h2>List Topic</h2>

<h2>List Curses</h2>

<div class="form-group">
    @Html.ActionLink(
             "Create a new Course",
             "Create",
             "Topics",
             null,
             new { @class = "btn btn-primary" }
             )
</div>
<table class="table">
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Course</th>
        <th scope="col">Action</th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Description
            </td>
            <td>
                @item.Name
            </td>
            <td>
                @item.Course.Name
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Topic", "SlectbyId", new { id = item.Id }, new { @class = "btn btn-danger" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn - warning" })
            </td>
        </tr>
    }

</table>